### PR TITLE
Reviewed code, wrapped up some strings in code to string resources. Improved app RTL support. Added to .gitignore, TavernaMobile.iml

### PR DESCRIPTION
**Pull request by larrytech7**

### CODE REVIEW

**Comment by therajanmaurya** [comment]
Hi, @larrytech7  put your app/build and  TavernaMobile2.iml folder in git ignore.
and update your PR.

**Comment by stain** [comment]
Hi, @larrytech7, thanks for the pull request. 

Agree with @therajanmaurya that `app/build` must be excluded, should it be in `.gitignore`?

**Comment by larrytech7** [comment]
Yes it definitely goes inside .gitignore. I just forgot that
TavernaMobile.iml has to be in there also. Sending in a new Request in a
moment.

2016-06-13 13:54 GMT+01:00 Stian Soiland-Reyes <notifications@github.com>:

> Hi, @larrytech7 <https://github.com/larrytech7>, thanks for the pull
> request.
>
> Agree with @therajanmaurya <https://github.com/therajanmaurya> that
> app/build must be excluded, should it be in .gitignore?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/incubator-taverna-mobile/pull/17#issuecomment-225572485>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGMQfX5jyOg6NvOq2j3nfIv-EwcC11JOks5qLVMZgaJpZM4Izql2>
> .
>



-- 
*Akah Larry N.H*

*Android Platform Engineer*
*Founder IceTeck*
*www.iceteck.com*

Developing technologies for emergence and sustainable development.

**Comment by stain** [comment]
Hi, @larrytech7 - I'm unable to merge this as now there are merge conflicts and 1095 changed files. (!)

Would you be OK to close this pull request and try again?  Remember to check with `git diff apache/master` or "Files Changed" at GitHub before making the pull request.

**Pull request closed without merging**
