### PR TITLE
NullPointerException while loading Workflow Run History 

### PR DESCRIPTION
**Pull request by therajanmaurya**
OnClick View Button to look full workflow some time app crashing while loading the WorkFlow Run History.

```java
 @Override
    public void onLoadFinished(Loader<Workflow> workflowLoader, Workflow workflow) {
        runAdapter.setRunList(workflow.getWorkflow_runs());
        mRecyclerView.setAdapter(runAdapter);
    try {
        if (runAdapter.getRunList().size() == 0) {
            mRecyclerView.setVisibility(View.GONE);
            emptyRunHistoryTextView.setVisibility(View.VISIBLE);
        } else {
            mRecyclerView.setVisibility(View.VISIBLE);
            emptyRunHistoryTextView.setVisibility(View.GONE);
        }
    }catch(NullPointerException np){
        np.printStackTrace();
    }
    }
```

The NullPointer Exception was comming at the line `if (runAdapter.getRunList().size() == 0)`.
That is giving NullPointerException.

Bug Resolve :+1:

### CODE REVIEW

**Comment by ianwdunlop** [comment]
Thanks for the pull request. I'll hopefully take a look at it next week - means dusting off android studio etc!

**Comment by larrytech7** [comment]
I guess I'll take a look earlier also.
Cheers

**Comment by stain** [comment]
I see this pull request builds upon your earlier pull requests and #10 #11 and #12 - so I guess it makes sense to review/accept them in that order.

**Comment by ianwdunlop** [comment]
@Stian yes, I just replied to the latest one. I'll review them starting at #10

**Comment by therajanmaurya** [comment]
Thanks @stain  and @ianwdunlop.

To review my PR, Now I am working on other Issues.

**Comment by ianwdunlop** [comment]
Looks like pull requests #12 and #13 were actually part of pull request #11 so have been automatically merged in now.

**Pull request merged**
