### PR TITLE
Material Workflow and Favorite Card View Title and Image view overlapping 

### PR DESCRIPTION
**Pull request by therajanmaurya**
Workflow and Favorite cardview alignment done perfectly Here is the final Workflow and favorite Screenshot :

APK
[app-debug.zip](https://github.com/apache/incubator-taverna-mobile/files/164765/app-debug.zip)

ScreenShot:
12804014_998282330292741_894114467_n
12825402_998282316959409_78159705_n

### CODE REVIEW

**Comment by larrytech7** [comment]
The images could preferably use circular and smaller images to allow space
for longer titles. I think the current feel is clean anyway.

cheers

2016-03-09 9:57 GMT+01:00 Rajan Maurya <notifications@github.com>:

> Workflow and Favorite cardview alignment done perfectly Here is the final
> Workflow and favorite Screenshot :
>
> APK
> app-debug.zip
> <https://github.com/apache/incubator-taverna-mobile/files/164765/app-debug.zip>
>
> ScreenShot:
> [image: 12804014_998282330292741_894114467_n]
> <https://cloud.githubusercontent.com/assets/5724482/13630013/ec34b2f2-e602-11e5-91cf-16f37d473857.jpg>
> [image: 12825402_998282316959409_78159705_n]
> <https://cloud.githubusercontent.com/assets/5724482/13630015/ed8094f0-e602-11e5-9bc3-58b7ed95c394.jpg>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/apache/incubator-taverna-mobile/pull/11
> Commit Summary
>
>    - design support library added and images moved to drawable and
>    implementing Material Navigation drawer
>    - Style theme added
>    - chaning images into drawable and change - to _ in images names and
>    removing Material library and Added design support library
>    - Material Design Navigation drawer Implemented
>    - Material ViewPager Implemented done
>    - Status bar color fix and final touchup to Material
>    NavigationBar,ViewPager and TabLayout
>    - workflow cardview item alignment done
>    - final cardview alignment
>    - Cardview Showing perfect and full : final
>
> File Changes
>
>    - *M* app/build.gradle
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-0>
>    (13)
>    - *M* app/src/main/AndroidManifest.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-1>
>    (2)
>    - *M*
>    app/src/main/java/org/apache/taverna/mobile/activities/DashboardMainActivity.java
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-2>
>    (312)
>    - *M*
>    app/src/main/java/org/apache/taverna/mobile/activities/FlashScreenActivity.java
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-3>
>    (2)
>    - *M*
>    app/src/main/java/org/apache/taverna/mobile/activities/LoginActivity.java
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-4>
>    (2)
>    - *M*
>    app/src/main/java/org/apache/taverna/mobile/adapters/FavoriteWorkflowAdapter.java
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-5>
>    (10)
>    - *M*
>    app/src/main/java/org/apache/taverna/mobile/fragments/WorkflowItemFragment.java
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-6>
>    (3)
>    - *A*
>    app/src/main/java/org/apache/taverna/mobile/fragments/Workflow_viewpager.java
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-7>
>    (113)
>    - *M*
>    app/src/main/java/org/apache/taverna/mobile/fragments/workflowdetails/WorkflowRunHistoryFragment.java
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-8>
>    (2)
>    - *R* app/src/main/res/anim/zoomin.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-9>
>    (0)
>    - *R* app/src/main/res/anim/zoomout.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-10>
>    (0)
>    - *A* app/src/main/res/drawable-hdpi/ic_menu.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-11>
>    (0)
>    - *A* app/src/main/res/drawable-mdpi/ic_menu.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-12>
>    (0)
>    - *A* app/src/main/res/drawable-xhdpi/ic_menu.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-13>
>    (0)
>    - *A* app/src/main/res/drawable-xxhdpi/ic_menu.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-14>
>    (0)
>    - *A* app/src/main/res/drawable-xxxhdpi/ic_menu.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-15>
>    (0)
>    - *R* app/src/main/res/drawable/ic_about_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-16>
>    (0)
>    - *R* app/src/main/res/drawable/ic_dashboard_home_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-17>
>    (0)
>    - *R* app/src/main/res/drawable/ic_download__web.jpg
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-18>
>    (0)
>    - *R* app/src/main/res/drawable/ic_download_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-19>
>    (0)
>    - *R* app/src/main/res/drawable/ic_downloadworkflow_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-20>
>    (0)
>    - *R* app/src/main/res/drawable/ic_launcher_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-21>
>    (0)
>    - *R* app/src/main/res/drawable/ic_loading_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-22>
>    (0)
>    - *R* app/src/main/res/drawable/ic_logout_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-23>
>    (0)
>    - *R* app/src/main/res/drawable/ic_markworkflow_selected_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-24>
>    (0)
>    - *R* app/src/main/res/drawable/ic_markworkflow_unselected_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-25>
>    (0)
>    - *R* app/src/main/res/drawable/ic_openwk_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-26>
>    (0)
>    - *R* app/src/main/res/drawable/ic_poweredby_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-27>
>    (0)
>    - *R* app/src/main/res/drawable/ic_quit_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-28>
>    (0)
>    - *R* app/src/main/res/drawable/ic_setting_workflows_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-29>
>    (0)
>    - *R* app/src/main/res/drawable/ic_usage_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-30>
>    (0)
>    - *R* app/src/main/res/drawable/ic_user_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-31>
>    (0)
>    - *R* app/src/main/res/drawable/ic_viewworkflow_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-32>
>    (0)
>    - *R* app/src/main/res/drawable/icuserprofiles_web.png
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-33>
>    (0)
>    - *M* app/src/main/res/layout-land/activity_dashboard_main.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-34>
>    (68)
>    - *M* app/src/main/res/layout/activity_dashboard_main.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-35>
>    (69)
>    - *M* app/src/main/res/layout/favorite_item_layout.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-36>
>    (47)
>    - *M* app/src/main/res/layout/fragment_workflow_detail.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-37>
>    (2)
>    - *A* app/src/main/res/layout/nav_header.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-38>
>    (55)
>    - *A* app/src/main/res/layout/viewpager_workflow.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-39>
>    (56)
>    - *M* app/src/main/res/layout/workflow_item_layout.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-40>
>    (312)
>    - *A* app/src/main/res/menu/drawer_view.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-41>
>    (46)
>    - *A* app/src/main/res/values-v21/styles.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-42>
>    (26)
>    - *A* app/src/main/res/values/colors.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-43>
>    (7)
>    - *M* app/src/main/res/values/dimens.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-44>
>    (3)
>    - *M* app/src/main/res/values/styles.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-45>
>    (21)
>    - *M* build.gradle
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-46>
>    (2)
>    - *M* build/intermediates/dex-cache/cache.xml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-47>
>    (75)
>    - *A* incubator-taverna-mobile.iml
>    <https://github.com/apache/incubator-taverna-mobile/pull/11/files#diff-48>
>    (19)
>
> Patch Links:
>
>    - https://github.com/apache/incubator-taverna-mobile/pull/11.patch
>    - https://github.com/apache/incubator-taverna-mobile/pull/11.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-taverna-mobile/pull/11>.
>



-- 
*Akah Larry N.H*

*Android Platform Engineer*
*Founder IceTeck*
*www.iceteck.com*

Developing technologies for emergence and sustainable development.

**Comment by therajanmaurya** [comment]
@larrytech7  , You are saying author image may be circular  and Title of workflow larger ?

**Comment by larrytech7** [comment]
Not that title of workflow should be larger but that when it's longer, it
should not span through several lines.

Le jeu. 10 mars 2016 05:47, Rajan Maurya <notifications@github.com> a
écrit :

**Comment by therajanmaurya** [comment]
Ok I increases the Title 16dp to 18dp. I think that's good for reading.

12833407_999514076836233_1863686141_n

I think it can be merged now. Or is there anything else should I add?

**Pull request merged**
