### PR TITLE
DashboardActivity Improvements

### PR DESCRIPTION
**Pull request by Hiteshgautam01**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the checks with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Hiteshgautam01** [comment]
<h3 align= "center" >UI after changes</h3>
<h1 align="center">

**Comment by Hiteshgautam01** [comment]
Hey @sagar15795 , can you first review this PR. If we are keeping these changes then  i will move the values to the dimens.xml

**Comment by sagar15795** [comment]
@Hiteshgautam01 What are the changes in UI?

**Comment by Hiteshgautam01** [comment]
@sagar15795 item of the recycler view for workflows on the dashboard is different now. I am also currently implementing the material search bar that suits these changes.

**Comment by sagar15795** [comment]
@Hiteshgautam01 I think in place of the date we need to move workflow type.

**Comment by Hiteshgautam01** [comment]
@sagar15795, I also agree with you on this. That's why I replace the date and workflow type as shown in the picture below.
device-2018-07-12-024814

**Comment by sagar15795** [comment]
@Hiteshgautam01 Also move all dimens constant to dimens.xml file

**Comment by Hiteshgautam01** [comment]
@sagar15795 Done.

**Pull request merged**
