### PR TITLE
Improved Project Structure, Refactored file's , Deleted Unused Files, Replaced png's with vector assets xml's

### PR DESCRIPTION
**Pull request by Hiteshgautam01**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the checks with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by sagar15795** [comment]
@Hiteshgautam01 Please fix the conflict.

**Comment by Hiteshgautam01** [comment]
@sagar15795 I have resolved the conflicts. Now you can review.

**Comment by ianwdunlop** [comment]
Any progress on this?

**Comment by sagar15795** [comment]
@ianwdunlop I think we can close this also. because this PR contains the only reformated code which we can do later.

**Pull request closed without merging**
