### PR TITLE
Removing incorrect messages under textfields

### PR DESCRIPTION
**Pull request by Hiteshgautam01**

### CODE REVIEW

**Comment by nyu-zeeshan** [comment]
You need not send a new PR. The build will pass once the previous PR is merged. 👍

**Comment by nyu-zeeshan** [comment]
@Hiteshgautam01 
please close and reopen the PR to restart the build.

**Comment by sagar15795** [comment]
@Hiteshgautam01 Merge the master branch code to your fork.

**Comment by nyu-zeeshan** [comment]
@sagar15795 
I'm fairly new ti GitHub but I don't think @Hiteshgautam01 needs to do that. If the build restarts, it will pass.

**Comment by sagar15795** [comment]
@nyu-zeeshan 
He needs to update the PR branch's Travis config which you have updated So he just need to merge it into his fork

**Pull request closed without merging**
