### PR TITLE
 Dagger 2.11 Implementation

### PR DESCRIPTION
**Pull request by Hiteshgautam01**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the checks with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Hiteshgautam01** [comment]
This PR is Currently Under Progress.

**Comment by sagar15795** [comment]
@Hiteshgautam01 Please fix Travis issue.

**Comment by sagar15795** [comment]
@Hiteshgautam01 I think it becomes very chaos with dagger 2.11. I think we have to use 2.8 for better simplification. Please revert to  dagger 2.8 version.

**Comment by Hiteshgautam01** [comment]
Okay @sagar15795, I am reverting the code to dagger 2.8 and i will open a separate PR for that.

**Pull request closed without merging**
